/**
  ******************************************************************************
  * @file    highglowg_fsm.h
  * @author  MEMS Software Solutions Team
  * @brief   High-g Low-g configuration file
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2025 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef HIGHGLOWG_FSM_H
#define HIGHGLOWG_FSM_H

#ifdef __cplusplus
extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
#include <stdint.h>

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef MEMS_UCF_EXT_SHARED_TYPES
#define MEMS_UCF_EXT_SHARED_TYPES

/*
 * UCF extended format supports the following commands:
 * - MEMS_UCF_OP_READ: read the register at the location specified by the
 *   "address" field ("data" field is ignored)
 * - MEMS_UCF_OP_WRITE: write the value specified by the "data" field at the
 *   location specified by the "address" field
 * - MEMS_UCF_OP_DELAY: wait the number of milliseconds specified by the "data"
 *   field ("address" field is ignored)
 * - MEMS_UCF_OP_POLL_SET: poll the register at the location specified by the
 *   "address" field until all the bits identified by the mask specified by the
 *   "data" field are set to 1
 * - MEMS_UCF_OP_POLL_RESET: poll the register at the location specified by the
 *   "address" field until all the bits identified by the mask specified by the
 *   "data" field are reset to 0
 */

#define MEMS_UCF_OP_READ       0
#define MEMS_UCF_OP_WRITE      1
#define MEMS_UCF_OP_DELAY      2
#define MEMS_UCF_OP_POLL_SET   3
#define MEMS_UCF_OP_POLL_RESET 4

typedef struct
{
  uint8_t op;
  uint8_t address;
  uint8_t data;
} ucf_line_ext_t;

#endif /* MEMS_UCF_EXT_SHARED_TYPES */

/* LSM6DSV256X configuration array generated by MEMS Studio */
static const ucf_line_ext_t highglowg_fsm[] =
{
  { .op = MEMS_UCF_OP_WRITE, .address = 0x10, .data = 0x00, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x11, .data = 0x00, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x01, .data = 0x80, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x05, .data = 0x00, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x04, .data = 0x00, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x5F, .data = 0x73, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x46, .data = 0x03, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x0B, .data = 0x03, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x0F, .data = 0x00, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x0A, .data = 0x00, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x0E, .data = 0x00, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x17, .data = 0x40, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x02, .data = 0x11, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x08, .data = 0x7A, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x08, .data = 0x7C, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x02, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x08, .data = 0x7E, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x04, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x02, .data = 0x41, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x08, .data = 0x00, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x70, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x50, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x24, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x80, }, //0x80 //low g threshold
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x4A, }, //0x4a
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xA8, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xA8, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x02, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x02, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x08, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x08, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x26, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x66, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x12, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xF7, }, //0x66
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x05, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xC7, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x77, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x99, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xF8, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x33, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x66, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xF7, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x57, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x44, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x88, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x99, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xF8, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xF5, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x22, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x70, }, //0x20 //high-g threshold
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x50, }, //0x4c
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x24, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x20, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x4C, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xA8, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xA8, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x03, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x03, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x04, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x04, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x23, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x09, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x52, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x01, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x66, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x12, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x05, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xC7, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x77, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x99, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x33, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x66, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x57, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x44, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x88, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x99, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0xF5, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x22, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x09, .data = 0x00, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x02, .data = 0x01, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x17, .data = 0x02, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x05, .data = 0x01, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x04, .data = 0x00, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x01, .data = 0x00, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x5E, .data = 0x02, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x5F, .data = 0x00, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x10, .data = 0x09, },
  { .op = MEMS_UCF_OP_WRITE, .address = 0x11, .data = 0x00, },
};

#ifdef __cplusplus
}
#endif

#endif /* __HIGHGLOWG_FSM_H__ */
